configured_endpoints: 157
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/usacognition/devin-platform-2b88bfb5a67786f44529b32e08e52b3d3089b92edc5eed447f05afc1dded7fc8.yml
openapi_spec_hash: 982b25e880993ff947cba4e4c91f87bb
config_hash: 3ac8bad9f0f6d5831fdc0f02b3ff2ddf
