configured_endpoints: 157
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/usacognition/devin-platform-d2f50fdb8ad8ad5a071ac4fef1b956e0ec9d5c591eb912f6eb1ee2746e2e4112.yml
openapi_spec_hash: 708174b0bd921479ce9e8ba128a5e38c
config_hash: 3ac8bad9f0f6d5831fdc0f02b3ff2ddf
